// Code generated by Wire protocol buffer compiler, do not edit.
// Source file: inventory.proto
package tech.harrynull.invtracker.proto

import com.squareup.wire.FieldEncoding
import com.squareup.wire.Message
import com.squareup.wire.ProtoAdapter
import com.squareup.wire.ProtoReader
import com.squareup.wire.ProtoWriter
import com.squareup.wire.WireField
import kotlin.Any
import kotlin.AssertionError
import kotlin.Boolean
import kotlin.Deprecated
import kotlin.DeprecationLevel
import kotlin.Int
import kotlin.Nothing
import kotlin.String
import kotlin.hashCode
import kotlin.jvm.JvmField
import okio.ByteString

class SearchOptions(
  /**
   * include inactive items, default false
   */
  @field:WireField(
    tag = 1,
    adapter = "com.squareup.wire.ProtoAdapter#BOOL"
  )
  val showInactive: Boolean? = null,
  /**
   * show out of stock items only, default false
   */
  @field:WireField(
    tag = 2,
    adapter = "com.squareup.wire.ProtoAdapter#BOOL"
  )
  val outOfStockOnly: Boolean? = null,
  unknownFields: ByteString = ByteString.EMPTY
) : Message<SearchOptions, Nothing>(ADAPTER, unknownFields) {
  @Deprecated(
    message = "Shouldn't be used in Kotlin",
    level = DeprecationLevel.HIDDEN
  )
  override fun newBuilder(): Nothing = throw AssertionError()

  override fun equals(other: Any?): Boolean {
    if (other === this) return true
    if (other !is SearchOptions) return false
    return unknownFields == other.unknownFields
        && showInactive == other.showInactive
        && outOfStockOnly == other.outOfStockOnly
  }

  override fun hashCode(): Int {
    var result = super.hashCode
    if (result == 0) {
      result = unknownFields.hashCode()
      result = result * 37 + showInactive.hashCode()
      result = result * 37 + outOfStockOnly.hashCode()
      super.hashCode = result
    }
    return result
  }

  override fun toString(): String {
    val result = mutableListOf<String>()
    if (showInactive != null) result += """showInactive=$showInactive"""
    if (outOfStockOnly != null) result += """outOfStockOnly=$outOfStockOnly"""
    return result.joinToString(prefix = "SearchOptions{", separator = ", ", postfix = "}")
  }

  fun copy(
    showInactive: Boolean? = this.showInactive,
    outOfStockOnly: Boolean? = this.outOfStockOnly,
    unknownFields: ByteString = this.unknownFields
  ): SearchOptions = SearchOptions(showInactive, outOfStockOnly, unknownFields)

  companion object {
    @JvmField
    val ADAPTER: ProtoAdapter<SearchOptions> = object : ProtoAdapter<SearchOptions>(
      FieldEncoding.LENGTH_DELIMITED, 
      SearchOptions::class, 
      "type.googleapis.com/tech.harrynull.invtracker.proto.SearchOptions"
    ) {
      override fun encodedSize(value: SearchOptions): Int = 
        ProtoAdapter.BOOL.encodedSizeWithTag(1, value.showInactive) +
        ProtoAdapter.BOOL.encodedSizeWithTag(2, value.outOfStockOnly) +
        value.unknownFields.size

      override fun encode(writer: ProtoWriter, value: SearchOptions) {
        ProtoAdapter.BOOL.encodeWithTag(writer, 1, value.showInactive)
        ProtoAdapter.BOOL.encodeWithTag(writer, 2, value.outOfStockOnly)
        writer.writeBytes(value.unknownFields)
      }

      override fun decode(reader: ProtoReader): SearchOptions {
        var showInactive: Boolean? = null
        var outOfStockOnly: Boolean? = null
        val unknownFields = reader.forEachTag { tag ->
          when (tag) {
            1 -> showInactive = ProtoAdapter.BOOL.decode(reader)
            2 -> outOfStockOnly = ProtoAdapter.BOOL.decode(reader)
            else -> reader.readUnknownField(tag)
          }
        }
        return SearchOptions(
          showInactive = showInactive,
          outOfStockOnly = outOfStockOnly,
          unknownFields = unknownFields
        )
      }

      override fun redact(value: SearchOptions): SearchOptions = value.copy(
        unknownFields = ByteString.EMPTY
      )
    }
  }
}
